name: "Publish FCM PG image CD"

on:
  release:
    types: [ published ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: fluxconfig/fluxconfig.postgres

jobs:
  publish_fcm_pg_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
        
    if: startsWith(github.event.release.tag_name, 'v')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: extract_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and publish image
        uses: docker/build-push-action@v6
        with:
          context: postgres_image
          file: postgres_image/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.extract_version.outputs.version }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          build-args: |
            POSTGRES_VERSION=17.4
          